# This pipeline will:
# - Delete blobs.
# 
# 
#
# The following variables need to be provided to the pipeline:
#
# - subscriptionId           : Subscription Id.
# - resourceGroupName        : The name for the Resource Group where vm will be created.
# - snapshotNameOs           : Name for snapshot containing the OS.
# - snapshotNameData         : Name for snapshot containing the Data.
# - location                 : Location for Managed Disks.
# - osDiskName               : Name for Managed Disk containing the OS.
# - dataDiskName             : Name for Managed Disk containing the data.
# - diskSizeOs               : The size for disk containing OS.
# - diskSizeData             : The size for disk containing data.
# - vhdUriOS                 : Uri to image in Storage Account, for the OS.
# - vhdUriData               : Uri to image in Storage Account, for the data.
# - storageType              : Storage type for Managed Disk
# - osType                   : Type of OS (linux, windows)
# - hyperVGeneration         : Generation for HyperV (v1/v2).
# - vmSize                   : Size for vm.
# - virtualMachineName       : Name for vm.
#
#
# This pipeline also expects an Azure (Resource Manager) service connection in Azure DevOps with the name 'MyAzureServiceConnection'.


trigger: none
pr: none

pool:
  name: easec-pool
  
variables:
  subscriptionId: "0ac447d7-fbc3-4d3d-84d4-37bb9a71e089"
  resourceGroupName: "snapshot-rg"
  storageAccount: "snapshottestsa"
  containerName: "snapshot"

stages:

- stage: Delete_blobs
  jobs:
  - job:
    steps:
     - task: AzureCLI@2
       inputs:
         azureSubscription: 'AzureServiceConnection'
         scriptType: pscore
         scriptLocation: inlineScript
         inlineScript: 
          $blobList= az storage blob list --query "[].name" --account-name "$(storageAccount)" --container-name "$(containerName)" --sas-token "$(token)"
          echo "Blobs:$blobList"